before_script:
- sudo apt-get update -qq
- sudo apt-get install git -y
- "git --git-dir /tmp/gcloud_history/.git checkout master"
- ".travis/setup_git_keys.sh"
- ".travis/install_gcloud_sdk.sh"
script: ".travis/sync_gcloud_releases.sh"
after_success:
- ".travis/push_results_github.sh"
env:
  global:
    secure: VAFnhz8CP9PFyHR4cMLcCziJD8kG2LZcHCIen+uC+Zw7iR0maZM0Y0BSoMNv+LEMWcOxpbx17j2zMmYTUYmvMoPI4STz48YlgSafXKB0R22gmLiSr8xhRvpEV6Gp38EQRVbkepz3QNdU/kHQ5BWnVSu3P1QlRyNJOHDBihvkDpzXteMJpHS0BVwDG9AP2DwK12dNCg98ua0rwjvA1gEaGqLdfaXWyrnINNCbvM/XJjVDat8qHm3D5ssHZwu5+xVnDdQHNaPBbTRBfDS5h1dw4qhaCo5oYeyBd5DGjWyyw2krgPh2hGCMTFPU0c5coVBf/OzfTUTfKaoVh+aCDOjytPOpk0LqmxkYkE3TrWHi73mmqiY+upJgXnso8DT/Gl/GyDMZIE54TKXv5cjwbPfp89nENq7/1ZARlb+mNFsIRpBgEM0b7W0m4aMQPOcUDjpeOTTHm4qQyuaRvKPZCvd91hRDIk592VP+TtfPvYH1JyCjzivm0Z38HZO8XODjyRlXFeRxRnT3L5tw/aD2NOr6uq20NbDC7vPJYOPCN0PMFPeW8pB0rM9/ZYXm7KtxbilBxhTjl61BZpHGnIiTqbnczq1vm905+vYRI8Tvt27rzvGCEN+LjVktGKfQ5kc48BzmfMI7UaNQ5m8u0kX6l6Dg92Ixj1jIx7GXeRPHM3Vk0J0=
